import pool from '../config/db.js';

export const getCustomerByEmailModel = async (email) => {
    const [result] = await pool.query(
        'select * from customer where email = ?',
        [email]
    );
    console.log(result[0])
    return result[0];
}

export const getCustomerByPhoneModel = async (phone) => {
    console.log(phone)
    const [result] = await pool.query(
        'select * from customer where phone = ?',
        [phone]
    );
    console.log(result[0])
    return result[0];
}

//get employees & system user by email or phone
// export const getCustomerByEmailORPswdModel = async (credintial) => {
//     const [result] = await pool.query(
//         'SELECT customer_id, email, role, phone, staus FROM customer WHERE staus = ? AND (email = ? OR phone = ?)',
//         ['active',credintial, credintial]
//     );

//     console.log(result[0].email)
//     return result[0];
// }

//get customers by customer id

// Get customers by email or phone
export const getCustomerByEmailORPswdModel = async (credential) => {
    const [result] = await pool.query(
        'SELECT customer_id, pasword as password, email, role, phone, staus, refresh_token FROM customer WHERE staus = ? AND (email = ? OR phone = ?)',
        ['active', credential, credential]
    );

    if (result.length === 0) return null; // Prevent accessing undefined index

    console.log("Customer Found:", result[0].email);
    return result[0];
};

export const getCustomersByCusIdModel = async (empId) => {
    const [result] = await pool.query(
        'select * from customer where pasword IS NOT NULL and customer_id = ?',
        [empId]
    );
    console.log(result[0])
    return result[0];
}

export const addCustomerModel = async (name, email, address, phone) => {
    const create_date = new Date().toISOString().split('T')[0];
    const [result] = await pool.query(
        'INSERT INTO customer (name, email, role, address, phone, staus, create_date) VALUES (?, ?, ?, ?, ?, ?, ?)',
        [name, email, 'customer', address, phone, 'active', create_date]
    );
    // Fetch the generated customer_id (since it's generated by trigger)
    const [rows] = await pool.query(
        'SELECT * FROM customer WHERE email = ? AND phone = ? ORDER BY create_date DESC LIMIT 1',
        [email, phone]
    );
    return rows[0];
}

//register customer 
export const registerCustomerModel = async (password, customer_id) => {
    const [result] = await pool.query(
        'UPDATE customer SET pasword = ? WHERE customer_id = ?',
        [password, customer_id]
    );
    return result[0];
}

export const getCusName = async (id) => {
  const [result] = await pool.query(
        `SELECT name FROM customer WHERE customer_id = ?`,
      [id]
    );
  return result[0].name;
};

// Add to models/customerModel.js
export const getAllCustomersModel = async () => {
  const [rows] = await pool.query(
    `SELECT customer_id, name, email, phone, address, create_date, staus 
     FROM customer 
     WHERE role = 'customer'`
  );
  return rows;
};

export const updateCustomerModel = async (customerId, updateData) => {
  const { name, email, phone, address, staus } = updateData;
  
  // Validate input parameters
  if (!customerId || !name || !email || !phone) {
    throw new Error('Missing required fields');
  }

  await pool.query(
    `UPDATE customer 
     SET name = ?, email = ?, phone = ?, address = ?, staus = ?
     WHERE customer_id = ?`,
    [name, email, phone, address || '', staus || 'active', customerId]
  );
  
  return getCustomersByCusIdModel(customerId);
};

// Add to models/bookingModel.js (create if not exists)
export const getBookingsByCustomerIdModel = async (customerId) => {
  const [rows] = await pool.query(
    `SELECT b.booking_id, b.booking_date, b.status, b.total_price, 
            b.number_of_guests, v.venue_name
     FROM booking b
     JOIN venue v ON b.venue_id = v.venue_id
     WHERE b.customer_id = ?`,
    [customerId]
  );
  return rows;
};

export const searchCustomerByTerm = async (searchTerm) => {
  const query = `
    SELECT customer_id, name, email, phone, address, create_date, staus 
    FROM customer 
    WHERE role = 'customer'
      AND (name LIKE ? 
           OR email LIKE ? 
           OR customer_id LIKE ?)
  `;
  
  const searchValue = `%${searchTerm}%`;
  const [results] = await pool.query(query, 
    [searchValue, searchValue, searchValue]
  );
  return results;
};