import pool from '../config/db.js';

export const getCustomerByEmailModel = async (email) => {
  const conn = await pool.getConnection();
  try {
    const [result] = await conn.query(
      'select * from customer where email = ?',
      [email]
    );
    return result[0];
  } finally {
    conn.release();
  }
}

export const getCustomerByPhoneModel = async (phone) => {
  const conn = await pool.getConnection();
  try {
    const [result] = await conn.query(
      'select * from customer where phone = ?',
      [phone]
    );
    return result[0];
  } finally {
    conn.release();
  }
}

// Get customers by email or phone
export const getCustomerByEmailORPswdModel = async (credential) => {
  const conn = await pool.getConnection();
  try {
    const [result] = await conn.query(
      'SELECT customer_id, pasword as password, email, role, phone, staus, refresh_token FROM customer WHERE staus = ? AND (email = ? OR phone = ?)',
      ['active', credential, credential]
    );

    if (result.length === 0) return null; // Prevent accessing undefined index
    return result[0];
  } finally {
    conn.release();
  }
};

export const getCustomersByCusIdModel = async (empId) => {
  const conn = await pool.getConnection();
  try {
    const [result] = await conn.query(
      'select * from customer where pasword IS NOT NULL and customer_id = ?',
      [empId]
    );
    return result[0];
  } finally {
    conn.release();
  }
}

export const addCustomerModel = async (name, email, address, phone) => {
  const conn = await pool.getConnection();
  const create_date = new Date().toISOString().split('T')[0];
  try {
    const [result] = await conn.query(
      'INSERT INTO customer (name, email, role, address, phone, staus, create_date) VALUES (?, ?, ?, ?, ?, ?, ?)',
      [name, email, 'customer', address, phone, 'inactive', create_date]
    );
    // Fetch the generated customer_id (since it's generated by trigger)
    const [rows] = await conn.query(
      'SELECT * FROM customer WHERE email = ? AND phone = ? ORDER BY create_date DESC LIMIT 1',
      [email, phone]
    );
    return rows[0];
  } catch (err) {
    console.error("Error inserting customer:", err);
    throw err;
  } finally {
    conn.release(); // ✅ Always release the connection
  }
}

//register customer 
export const registerCustomerModel = async (password, customer_id) => {
  const conn = await pool.getConnection();
  console.log("model", password, customer_id)
  try {
    const [result] = await conn.query(
      'UPDATE customer SET pasword = ?, staus = ? WHERE customer_id = ?',
      [password, 'active', customer_id]
    );
    return result[0];
  } finally {
    conn.release();
  }
}

export const getCusName = async (id) => {
  const conn = await pool.getConnection();
  try {
    const [result] = await conn.query(
      `SELECT name FROM customer WHERE customer_id = ?`,
      [id]
    );
    return result[0].name;
  } finally {
    conn.release();
  }
};

// Add to models/customerModel.js
export const getAllCustomersModel = async () => {
  const conn = await pool.getConnection();
  try {
    const [rows] = await conn.query(
      `SELECT customer_id, name, email, phone, address, create_date, staus 
       FROM customer 
       WHERE role = 'customer'`
    );
    return rows;
  } finally {
    conn.release();
  }
};

export const updateCustomerModel = async (customerId, updateData) => {
  const { name, email, phone, address, staus } = updateData;
  const conn = await pool.getConnection();
  // Validate input parameters
  if (!customerId || !name || !email || !phone) {
    throw new Error('Missing required fields');
  }

  try {
    await conn.query(
      `UPDATE customer 
       SET name = ?, email = ?, phone = ?, address = ?, staus = ?
       WHERE customer_id = ?`,
      [name, email, phone, address || '', staus || 'active', customerId]
    );

    return getCustomersByCusIdModel(customerId);
  } finally {
    conn.release();
  }
};

// Add to models/bookingModel.js (create if not exists)
export const getBookingsByCustomerIdModel = async (customerId) => {
  const conn = await pool.getConnection();
  try {
    const [rows] = await conn.query(
      `SELECT b.booking_id, b.booking_date, b.status, b.total_price, 
              b.number_of_guests, v.venue_name
       FROM booking b
       JOIN venue v ON b.venue_id = v.venue_id
       WHERE b.customer_id = ?`,
      [customerId]
    );
    return rows;
  } finally {
    conn.release();
  }
};

export const deleteCustomerIdModel = async (customerId) => {
  console.log('Deleting customer with ID:', customerId);
  const conn = await pool.getConnection();
  try {
    const [rows] = await conn.query(
      `delete from customer where customer_id = ?`,
      [customerId]
    );
    return rows;
  } finally {
    conn.release();
  }
};

export const searchCustomerByTerm = async (searchTerm) => {
  const conn = await pool.getConnection();
  try {
    const query = `
      SELECT customer_id, name, email, phone, address, create_date, staus 
      FROM customer 
      WHERE role = 'customer'
        AND (name LIKE ? 
             OR email LIKE ? 
             OR customer_id LIKE ?)
    `;
  
    const searchValue = `%${searchTerm}%`;
    const [results] = await conn.query(query,
      [searchValue, searchValue, searchValue]
    );
    return results;
  } finally {
        conn.release();
    }
};